---
# GMT
:concurrency: 20
:queues:
  - default
  - push
  - pull
  - mailers
  - remove
  - elasticsearch
:schedule:
  subscriptions_scheduler:
    cron: '0 19,0 * * *'
    class: Scheduler::SubscriptionsScheduler
  delete_duplicated_subscription_retry_job_scheduler:
    cron: '20 19,0 * * *'
    class: Scheduler::DeleteDuplicatedSubscriptionRetryJobScheduler
  media_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(18..20) %> * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(15..16) %> * * *'
    class: Scheduler::FeedCleanupScheduler
  doorkeeper_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(0..2) %> * * 0'
    class: Scheduler::DoorkeeperCleanupScheduler
  user_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(4..6) %> * * *'
    class: Scheduler::UserCleanupScheduler
  subscriptions_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(1..3) %> * * 0'
    class: Scheduler::SubscriptionsCleanupScheduler
  ip_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::IpCleanupScheduler
  email_scheduler:
    cron: '0 10 * * 2'
    class: Scheduler::EmailScheduler
  delete_elasticsearch_documents_worker:
    cron: '*/2 * * * *'
    class: Scheduler::DeleteElasticsearchDocumentsWorker
  trend_tag_scheduler:
    cron: '*/30 * * * *'
    class: Scheduler::TrendTagScheduler
  pawoo_report_target_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(2..4) %> * * *'
    class: Pawoo::Scheduler::ReportTargetCleanupScheduler
  pawoo_refresh_popular_account_scheduler:
    cron: '30 18 * * 0'
    class: Pawoo::Scheduler::RefreshPopularAccountScheduler
  pawoo_refresh_sitemap_statuses_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(18..20) %> * * *'
    class: Pawoo::Scheduler::PrepareSitemapScheduler
