---
<<<<<<< HEAD
:concurrency: 20
=======
:concurrency: 5
>>>>>>> 8963f8c3c2630bfcc377a5ca0513eef5a6b2a4bc
:queues:
  - default
  - push
  - pull
  - mailers
<<<<<<< HEAD
  - remove
  - elasticsearch
=======
:schedule:
  subscriptions_scheduler:
    cron: '0 5 * * *'
    class: Scheduler::SubscriptionsScheduler
  media_cleanup_scheduler:
    cron: '5 4 * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '0 0 * * *'
    class: Scheduler::FeedCleanupScheduler
>>>>>>> 8963f8c3c2630bfcc377a5ca0513eef5a6b2a4bc
