---
# GMT
:concurrency: 20
:queues:
  - default
  - push
  - pull
  - mailers
  - remove
  - elasticsearch
:schedule:
  subscriptions_scheduler:
    cron: '0 19,0 * * *'
    class: Scheduler::SubscriptionsScheduler
  media_cleanup_scheduler:
    cron: '5 19 * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '0 15 * * *'
    class: Scheduler::FeedCleanupScheduler
  doorkeeper_cleanup_scheduler:
    cron: '1 1 * * 0'
    class: Scheduler::DoorkeeperCleanupScheduler
  user_cleanup_scheduler:
    cron: '4 5 * * *'
    class: Scheduler::UserCleanupScheduler
  delete_elasticsearch_documents_worker:
    cron: '*/2 * * * *'
    class: Scheduler::DeleteElasticsearchDocumentsWorker
  trend_tag_scheduler:
    cron: '*/30 * * * *'
    class: Scheduler::TrendTagScheduler
  local_status_count_scheduler:
    cron: '*/10 * * * *'
    class: Scheduler::LocalStatusCountScheduler
