# c.f. https://dependabot.com/docs/config-file/
version: 1

update_configs:
  - package_manager: "ruby:bundler"

    directory: "/"

    # NOTE: securityはupdate_scheduleに関わらず即PRがくるのだが必須属性のため無いとエラーになるので仮で入れている
    update_schedule: "weekly"

    allowed_updates:
      - match:
          update_type: "security"

    # Enable. Only lockfile updates (ignore updates that require Gemfile changes)
    version_requirement_updates: "off"

  - package_manager: "javascript"

    directory: "/"

    # NOTE: securityはupdate_scheduleに関わらず即PRがくるのだが必須属性のため無いとエラーになるので仮で入れている
    update_schedule: "weekly"

    allowed_updates:
      - match:
          # Disable. Only top-level dependencies (and security patches for subdependencies)
          update_type: "security"

    # Enable. Only lockfile updates (ignore updates that require Gemfile changes)
    version_requirement_updates: "auto"


