name: pawoo-test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 1" # JST 9:00 (Mon)

env:
  CI: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.5.16
        env:
          POSTGRES_USER: root
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3.2.4
        ports:
          - 6379:6379
    container:
      image: ruby:2.5.7-stretch
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        LOCAL_HTTPS: true
        RAILS_ENV: test
        PARALLEL_TEST_PROCESSORS: 4
        ALLOW_NOPAM: true
        CONTINUOUS_INTEGRATION: true
        DISABLE_SIMPLECOV: true
    steps:
    - uses: actions/checkout@v1
    - name: Install system dependencies
      run: |
        apt update
        apt install apt-transport-https
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
        curl -sL https://deb.nodesource.com/setup_10.x | bash -
        apt update
        apt install -y yarn nodejs ffmpeg libicu-dev libidn11-dev libprotobuf-dev protobuf-compiler

    - name: Cache ruby dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: v1-ruby-dependencies-${{ hashFiles('.ruby-version') }}-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          v1-ruby-dependencies-${{ hashFiles('.ruby-version') }}-${{ hashFiles('Gemfile.lock') }}
          v1-ruby-dependencies-${{ hashFiles('.ruby-version') }}-
          v1-ruby-dependencies-
    - name: Cache node dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: v1-node-dependencies-${{ hashFiles('.nvmrc') }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          v1-node-dependencies-${{ hashFiles('.nvmrc') }}-${{ hashFiles('yarn.lock') }}
          v1-node-dependencies-${{ hashFiles('.nvmrc') }}-
          v1-node-dependencies-

    - name: bundle install
      run: bundle install --clean --jobs 4 --path ./vendor/bundle/ --retry 3 --with pam_authentication --without development production && bundle clean
    - name: yarn install
      run: yarn install --frozen-lockfile

    # - name: Run rubocop
    #   run: bundle exec rubocop --parallel
    - name: Run eslint
      run: yarn test:lint

    - name: Run jest
      run: yarn test:jest

    - name: Run rails assets:precompile
      run: ./bin/rails assets:precompile
    - name: Run rails error_page:generate
      run: ./bin/rails error_page:generate

    - name: Prepare DB
      run: ./bin/rails parallel:create parallel:load_schema parallel:prepare
    - name: Run rspec
      run: bundle exec parallel_test ./spec/ --group-by filesize --type rspec
